# Generated by Django 4.2.2 on 2023-06-13 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('headquarters_country', models.CharField(max_length=56)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('year_of_issue', models.DateField()),
                ('body_style', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('mileage', models.PositiveIntegerField()),
                ('exterior_color', models.CharField(max_length=30)),
                ('interior_color', models.CharField(max_length=30)),
                ('fuel_type', models.CharField(max_length=30)),
                ('transmission', models.CharField(max_length=50)),
                ('engine', models.CharField(max_length=50)),
                ('on_sale', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.brand')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.model')),
            ],
        ),
    ]
