# Generated by Django 4.2.2 on 2023-06-13 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_brand_options_alter_car_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10000000)]),
        ),
        migrations.AlterField(
            model_name='model',
            name='year_of_issue',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2050)]),
        ),
    ]
